[package]
name = "zkdrop-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[features]
default = ["std"]
std = []            # enable for host only

[lib]
crate-type = ["rlib"]